version: '2'
services:
  seed:
    image: akka-auto-scaling-sample:0.1
    ports:
      - "8558:8558"
      - "8080:8080"
#    - "2552:2552"
    environment:
      CLUSTER_PORT: 2552
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
      SEED_PORT_1600_TCP_PORT: 2552
  node:
      image: akka-auto-scaling-sample:0.1
#      ports:
#      - "8081:8080"
  #    - "2552:2552"
      environment:
        CLUSTER_PORT: 0
        CLUSTER_IP: ""
        SEED_PORT_1600_TCP_ADDR: seed
        SEED_PORT_1600_TCP_PORT: 2552
