kind: Service
apiVersion: v1
metadata:
  name: akka-bootstrap-demo
spec:
  type: NodePort
  selector:
    app: akka-bootstrap-demo
  ports:
  - protocol: TCP
    name: management
    port: 8558
    targetPort: management
  - protocol: TCP
    name: api
    port: 8080
    targetPort: api

